#!/usr/bin/with-contenv bash

if [[ 'On' == $ENCORE_DEV_SERVER ]]
then
    exec /usr/bin/yarn --cwd /var/www/app encore dev-server --host 0.0.0.0 --public http://localhost:8080 --disable-host-check --hot
else
    exec /usr/bin/yarn --cwd /var/www/app encore dev --watch
fi
