version: '2.4'

volumes:
    mongo_data: {}

services:
    js:
        container_name: js
        build:
            context: dockerfiles/js
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
            NODE_ENV: development
            MATTERMOST_WEBHOOK_URL: ""
            DOCKER_AUTH_USERNAME: ${DOCKER_AUTH_USERNAME}
            DOCKER_AUTH_EMAIL: ${DOCKER_AUTH_EMAIL}
            DOCKER_AUTH_PASSWORD: ${DOCKER_AUTH_PASSWORD}
        ports:
            - "80:3000"
        volumes:
            - ${APP_PATH}:/app:${CACHE_MODE}
            - /var/run/docker.sock:/var/run/docker.sock:${CACHE_MODE}
        mem_limit: 512m

    mongo: # Wekan requirement
        image: mongo
        container_name: mongo
        volumes:
            - mongo_data:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        hostname: mongo-express
        depends_on:
            - mongo
        ports:
            - "81:8081"

    filebeat:
        container_name: filebeat
        image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
        command: filebeat -e -strict.perms=false
        user: root
        hostname: ${FILEBEAT_HOSTNAME}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker:/var/lib/docker:ro
            - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
