version: '2.4'

services:
    python:
        build:
            context: dockerfiles/python
        container_name: python
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
            ENCORE_DEV_SERVER: ${ENCORE_DEV_SERVER}
            ENTRYPOINTS_FILE: ${ENTRYPOINTS_FILE}
            FLASK_ENV: ${FLASK_ENV}
            FLASK_APP: ${FLASK_APP}
            SECRET_KEY: ${SECRET_KEY}
            TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
        volumes:
            - ${APP_PATH}:/var/www/app:${CACHE_MODE}
        ports:
            - "80:5000"
            - "8080:8080"
        mem_limit: 2048m

    filebeat:
        container_name: filebeat
        image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
        command: filebeat -e -strict.perms=false
        user: root
        hostname: ${FILEBEAT_HOSTNAME}
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker:/var/lib/docker:ro
            - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
