version: '2.2'

volumes:
    elasticsearch_data: {}

services:
    php-fpm:
        container_name: php-fpm
        build:
            context: dockerfiles/php-fpm
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
            XDEBUG: ${XDEBUG}
            XDEBUG_REMOTE: ${XDEBUG_REMOTE}
            XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
            ENCORE_DEV_SERVER: ${ENCORE_DEV_SERVER}
        ports:
            - "8080:8080"
        volumes:
            - ${APP_PATH}:/var/www/symfony:${CACHE_MODE}
            - /var/run/docker.sock:/var/run/docker.sock:${CACHE_MODE}
        mem_limit: 4096m

    nginx:
        container_name: nginx
        image: shokohsc/alpine-nginx
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
        ports:
            - "80:80"
        volumes:
            - /var/log/nginx
            - ${APP_PATH}:/var/www/symfony:${CACHE_MODE}
            - ./nginx/symfony4.conf:/etc/nginx/conf.d/symfony.conf:${CACHE_MODE}
        depends_on:
            - php-fpm
        mem_limit: 8m

    varnish:
        container_name: varnish
        image: shokohsc/alpine-varnish
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
        ports:
            - "81:80"
        depends_on:
            - nginx
        mem_limit: 128m

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        mem_limit: 512m

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
        environment:
            SERVER_NAME: kibana
            LOGGING_QUIET: 'true'
        ports:
            - "82:5601"
        depends_on:
            - elasticsearch
        mem_limit: 512m

    filebeat:
        container_name: filebeat
        image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
        command: filebeat -e -strict.perms=false
        user: root
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker:/var/lib/docker:ro
            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        depends_on:
            - elasticsearch
            - kibana
        mem_limit: 64m

    sqlite:
        container_name: sqlite
        image: sqrt3/sqlite-web
        command: /db/data.db
        ports:
            - "83:8080"
        volumes:
            - ${APP_PATH}/var/:/db
        depends_on:
            - php-fpm
        mem_limit: 1024m
