version: '2.2'

volumes:
    elasticsearch_data: {}

services:
    php-fpm:
        container_name: php-fpm
        build:
            context: dockerfiles/php-fpm
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
            XDEBUG: ${XDEBUG}
            XDEBUG_REMOTE: ${XDEBUG_REMOTE}
            XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
            ENCORE_DEV_SERVER: ${ENCORE_DEV_SERVER}
        ports:
            - "8080:8080"
        volumes:
            - ${APP_PATH}:/var/www/symfony:${CACHE_MODE}
            - /var/run/docker.sock:/var/run/docker.sock:${CACHE_MODE}
        mem_limit: 4096m

    nginx:
        container_name: nginx
        image: shokohsc/alpine-nginx
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
        ports:
            - "80:80"
        volumes:
            - /var/log/nginx
            - ${APP_PATH}:/var/www/symfony:${CACHE_MODE}
            - ./config/nginx/symfony.conf:/etc/nginx/conf.d/symfony.conf:${CACHE_MODE}
        depends_on:
            - php-fpm
        mem_limit: 8m

    filebeat:
        container_name: filebeat
        image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
        command: filebeat -e -strict.perms=false
        user: root
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker:/var/lib/docker:ro
            - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
            # - ${CA_PATH}:/etc/ca.crt
        mem_limit: 64m
