version: '2.4'

volumes:
    elasticsearch_data: {}

services:
    node:
        container_name: node
        build:
            context: dockerfiles/node
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
            NODE_ENV: development
        ports:
            - "80:3000"
        volumes:
            - ${APP_PATH}:/app:${CACHE_MODE}
        mem_limit: 512m

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        mem_limit: 512m

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
        environment:
            SERVER_NAME: kibana
            LOGGING_QUIET: 'true'
        ports:
            - "82:5601"
        depends_on:
            - elasticsearch
        mem_limit: 512m

    filebeat:
        container_name: filebeat
        image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
        command: filebeat -e -strict.perms=false
        user: root
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/lib/docker:/var/lib/docker:ro
            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
        depends_on:
            - elasticsearch
            - kibana
        mem_limit: 64m
