version: '2.2'

services:
    php-fpm:
        container_name: php-fpm
        build:
            context: dockerfiles/php-fpm
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
            XDEBUG: ${XDEBUG}
            XDEBUG_REMOTE: ${XDEBUG_REMOTE}
            XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
        volumes:
            - /var/www/symfony
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:${CACHE_MODE}
        mem_limit: 4096m

    nginx:
        container_name: nginx
        image: shokohsc/alpine-nginx
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
        ports:
            - "80:80"
        volumes_from:
            - php-fpm
        depends_on:
            - php-fpm
        mem_limit: 50m

    varnish:
        container_name: varnish
        image: shokohsc/alpine-varnish
        environment:
            PGID: ${PGID}
            PUID: ${PUID}
            TZ: ${TIMEZONE}
        ports:
            - "8080:80"
        depends_on:
            - nginx
        mem_limit: 128m

    elasticsearch:
        container_name: elasticsearch
        build:
            context: elasticsearch/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"

    logstash:
        container_name: logstash
        build:
            context: logstash/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ./logstash/patterns:/opt/logstash/patterns
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
        volumes_from:
            - php-fpm
            - nginx
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        depends_on:
            - elasticsearch

    kibana:
        container_name: kibana
        build:
            context: kibana/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
        ports:
            - "81:5601"
        depends_on:
            - elasticsearch
