#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" www-data
usermod -o -u "$PUID" www-data

echo '
----------------------------------------------------------------------------
GID/UID
----------------------------------------------------------------------------'
echo "
User uid:    $(id -u www-data)
User gid:    $(id -g www-data)
----------------------------------------------------------------------------
"
chown www-data:www-data /www-data
chown www-data:www-data /config
chown www-data:www-data /defaults
